####################################################
#
# Welcome to Redcanari  Jekyll Template
#
# Product Link :  
# Version : v1.0.0
#
####################################################

# Site settings
title: "Redcanari  jekyll Website"
email: "info@redcanari.com"
logo_url: /assets/img/Logo.png
description: "Redcanari  is a responsive Jekyll template for your business website"
keywords: "jekyll, minimal jekyll, jekyll theme, responsive jekyll, seo friendly blog, super fast blog, responsive"
url: ""
baseurl: "" # the subpath of your site, e.g. /blog



# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives


# Site configuration for the Jekyll 2 Pagination Gem
pagination:
  enabled: false
  debug: true
  collection: 'posts'
  per_page: 1
  permalink: '/pages/:num/' # Pages are simple html files 
  title: ':title - page :num'
  limit: 0 
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 
  trail: 
    before: 2
    after: 
  extension: 'html'
  indexpage: 'index'

feed:
  collections:
    posts:
      path: "/index.xml"